# Generated by Django 2.2.10 on 2020-07-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200702_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='one_click_purcharsing',
            field=models.BooleanField(default=False),
        ),
    ]
