# Generated by Django 2.2.10 on 2020-07-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200702_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
