# Generated by Django 2.2.10 on 2020-07-04 04:56

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_order_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='modified_date',
            field=core.models.CustomDateTimeField(auto_now_add=True, null=True),
        ),
    ]
